version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - .env


  web_app:
    build: .
    command: bash start.sh
    ports:
      - '3334:3334'
    volumes:
      - '.:/open_todoist'
      - gems:/gems
    env_file:
      - .env
    depends_on:
      - postgres
    stdin_open: true
    tty: true
 
volumes:
  postgres:
  gems:
  web:

