version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$db_user
      - POSTGRES_PASSWORD=$db_pass


  web_app:
    build: .
    command: bash start.sh
    ports:
      - '3334:3334'
    volumes:
      - '.:/open_todoist'
      - gems:/gems
    depends_on:
      - postgres
 
volumes:
  postgres:
  gems:
  web:

