default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_pass'] %>
  port: <%= ENV['db_port'] || 5534 %>
  host: <%= ENV['db_host'] %>

development:
  <<: *default
  database: open_todoist_development

test:
  <<: *default
  database: open_todoist_test

production:
  <<: *default
  database: open_todoist_production
